$EXTEND
$NOMOD166
$STDNAMES(reg.def)
$SEGMENTED
$CASE
$NOEXPANDREGBANK
$MODEL(LARGE)

        NAME DC166_EXIT_TARGET

DC166_EXIT_TARGET_PR SECTION CODE WORD PUBLIC 'CLIBRARY'
        PUBLIC __dc166_exit_target
        EXTERN __EXIT:FAR ; KEEP_FAR

__dc166_exit_target PROC FAR
        JMPS SEG __EXIT,__EXIT
        RETS
__dc166_exit_target ENDP
DC166_EXIT_TARGET_PR ENDS

        REGDEF R0-R15
        END
