$EXTEND
$NOMOD166
$STDNAMES(reg.def)
$SEGMENTED
$CASE
$NOEXPANDREGBANK
$MODEL(LARGE)

        NAME DC166_HEAP_BOUNDS

DC166_HEAP_BOUNDS_PR SECTION CODE WORD PUBLIC 'CPROGRAM'
        PUBLIC _dc166_heap_begin
        PUBLIC _dc166_heap_end

_dc166_heap_begin PROC FAR
        MOV R4,#SOF ?C166_FHEAP_TOP
        MOV R5,#SEG ?C166_FHEAP_TOP
        RETS
_dc166_heap_begin ENDP

_dc166_heap_end PROC FAR
        MOV R4,#SOF ?C166_FHEAP_BOTTOM
        MOV R5,#SEG ?C166_FHEAP_BOTTOM
        RETS
_dc166_heap_end ENDP
DC166_HEAP_BOUNDS_PR ENDS

        EXTERN ?C166_FHEAP_BOTTOM:WORD
        EXTERN ?C166_FHEAP_TOP:WORD
        REGDEF R0-R15
        END
