$EXTEND
$NOMOD166
$STDNAMES(reg.def)
$SEGMENTED
$CASE
$NOEXPANDREGBANK
$MODEL(LARGE)

        NAME DC166_LIBC_HUGE_BOUNDARY

DC166_LIBC_BOUNDARY_RESERVATION SECTION HDAT WORD PUBLIC 'BOUNDARY'
        DS      020004h
DC166_LIBC_BOUNDARY_RESERVATION ENDS

        REGDEF R0-R15
        END
